[version]
version = '0.0.1'

[network]
host = '127.0.0.1'
port = 6000
socket_connection_timeout = 180
read_timeout = 5

[database]
max_connections = [30, 20, 10]      # High priority -> low priority
connection_timeout = 10.0
connection_refresh_interval = 500.0
connection_lease_duration = 120.0

[file]
file_cache_size = 65536
file_cache_ttl = 180
file_lock_ttl = 60
file_contention_timeout = 3.0
file_transfer_timeout = 6
cache_public_files = true
root_directory = 'files'
user_max_files = 256
user_max_storage = 268_435_456

[credentials]
credentials_dirname = 'credentials'
key_filename='key.pem'
certificate_filename='cert.crt'
ciphers='ECDHE-ECDSA-AES256-GCM-SHA384'
rollover_signature_length=256
rollover_grace_window=44800
rollover_data_filename='rollover.json'

[auth]
max_attempts = 5
lock_timeouts = [3600, 7200, 42600, 8400]
session_lifespan = 10800

[logging]
log_batch_size = 100
log_waiting_period = 1.0
log_interval = 5.0
log_queue_size = 1_048_576